package com.testnepal.enums;

public enum ConfigProperties {
	URL,
	BROWSER,
	OVERRIDEREPORTS,
	PASSEDSTEPSCREENSHOTS,
	FAILEDSTEPSCREENSHOTS,
	SKIPPEDSTEPSCREENSHOTS,
	RETRYFAILEDTESTS,
	FAILEDTESTRETRYCOUNT,
	AUTOREPORTOPEN,
}
